---
title: "The advantages of tic"
author: "Patrick Schratz, Kirill Müller"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Kirill Müller}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

old.hooks = fansi::set_knit_hooks(knitr::knit_hooks)
options(crayon.enabled = TRUE)
```

So, what's the advantage of using *tic* over the standard CI process?

1. Deployment to a Git repository is greatly simplified. 
   Update your repository with results from the CI build.

1. Support for R packages and other kinds of project (bookdown, blogdown, etc.), with predefined templates. 
   Set up your project to deploy rendered versions of your book or blog with a single push to Git.

1. Workflow specification in a single `.R` file, regardless of CI system used.  
   Forget about `.yml` files or web browser configurations.
   
Other minor advantages include the use of `rcmdcheck::rcmdcheck()` for package checking a and robust caching approach of dependencies.

## Easier deployment

You may know that CI services can be used to automatically deploy files. 
This means that these services can push certain files created during the build to repositories (Github, Gitlab, etc.).
A common use case is to build your `pkgdown` site and conditionally push changes to your repo.
This practice saves you from building the whole `pkgdown` site locally and then committing manually all the changed files - either Travis or Appveyor will do it for you! 
*tic* takes care of all the setup work (setting up SSH keys, permission granting for the repo on Github and the CI services).
In combination with `usethis::use_ci()` this whole preparation process is streamlined and needs only be called once for every repo by the user.

For more information on automatic deployment in *tic*, take a look [here](deployment.html).

## Support for various R projects

*tic* was developed with the aim to not only simplify R package development using CI services but also to support other R project types (bookdown, blogdown, drat, website and fighshare deployment). 

Each of these projects has its own standardized structure. 
*tic* detects this structure and adds templates tailored towards this specific project type to the repository when calling `usethis::use_ci()`.
See [here](tic.html#example-projects) for a list of supported project types including links to minimal example repositories. 

## CI-Agnostic workflows

What does "CI-Agnostic" mean and why do we need it?

You may have heard that multiple CI services exist in the wild.
Some only support specific operating systems or certain languages and for some you need to pay a monthly rate to use them.
What all have in common: They have their own way to specify their setup file, which is most often written in YAML and stored at the top-level directory of your repo.
This setup file controls what will be done in each run.

To give you an example how different these control files can be, take a look at these two examples from [Travis](https://github.com/tidyverse/dplyr/blob/master/.travis.yml) and [Appveyor](https://github.com/tidyverse/dplyr/blob/master/appveyor.yml).
While Travis is the only free CI service with an "official" support for R (maintained by the community, specifically by @jimhester), `Appveyor` currently requires quite some magic (e.g. `travis-tool.sh`) in the background to install a working R framework. 

We could list way more differences - but that's exactly the point when *tic* comes in!

- Rather than dealing with all the CI differences, *tic* enables the specification of the complete workflow in an external R script file `tic.R`.
- The commands specified in there will be understood on every CI service that is supported by *tic*.
- Furthermore, you can [emulate all the stages and steps locally](advantages.html#less-dependency-on-external-ci-control-commands) by calling `tic()`.
- You are independent from all the changes that are being made on the R setup for Travis or Appveyor ([more info]((advantages.html#less-dependency-on-external-ci-control-commands)).
- A `tic.R` workflow is usually shorter and easier to parse than a `.travis.yml` or `appveyor.yml` file.

So instead of learning how to specify specific tasks on different CI platforms, you only need to learn how to do with R commands.

## Less dependency on external CI control commands

Most CI services come with no (native) support for the R programming language.
For Travis and Appveyor, the support is provided by the R community.
For example, [r.rb](https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb) controls what happens if you set `language: r` on Travis.
All of the commands and arguments specified there can also be set in `tic.R` using R syntax.
So you are no longer dependent on the syntax and restrictions coming from [r.rb](https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb) but able to control the whole CI workflow in a single R file.

## Enhanced R package checking: `rcmdcheck()` > R CMD check

As a R package developer you are most likely used to call `devtools::check()` or directly `R CMD check` on your built package.
Usually also Travis will run `R CMD check` to check the R package.
*tic* instead uses  [*rcmdcheck*](https://github.com/r-lib/rcmdcheck), which can be seen as a wrapper around `R CMD build` and `R CMD check`.
It was developed by [Gabor Csardi](https://github.com/gaborcsardi).
*rcmdcheck* comes with several enhancements:

- Coloring of important steps, simplifying the readability of the log
- Enhanced and extended tracebacks of errors, especially errors in tests
- The whole check process is returned in a R object, making it easier to inspect eventual errors/warnings

Especially the extended log printing of errors on the CI service is a huge advantage - often enough, CI services cut log output of the console early, omitting important information about the error. 

Here is an short excerpt of the improved log output by *rcmdcheck* including an error message:

```r

```

## Caching of packages

When using *tic* all dependencies (the ones of the package and of also the ones of all stages of the CI build) are installed in the "before_install" stage. 
This has the advantage that all packages get added to the cache (even if they are just needed for deployment), speeding up subsequent builds substantially.

More information about the whole CI workflow can be found in the [Build lifecyle](build-lifecycle.html) vignette.

## Easier troubleshooting

*tic* comes with the ability to emulate the CI run locally and debug potential problems. 
This is possible because `tic.R` is a plain R file that will be sourced when calling `tic()`.
It will run all the stages and steps in the same order as it would happen on the CI service.

Sometimes CI builds error (even multiple times) and you don't know whether the error is caused by the CI service or by a wrong workflow specification on your side.

To make sure that you have no syntax errors in your `tic.R` file, all you need to do is to call `load_from_file()`.
In case you have errors, you will see them directly.
For example, removing a closing bracket on purpose in `tic.R` would return the following when calling `load_from_file()`:

```r
load_from_file()
Error in source(path, local = dsl) : tic.R:16:1: unexpected '}'
15:     add_step(step_push_deploy())
16: }
    ^
```

See [Troubleshooting: Running tic locally](advanced#troubleshooting-running-tic-locally) and [Troubleshooting: Entering the CI build](advanced#troubleshooting-entering-the-cI-build) for instructions on how to debug your CI build in more detail.
