---
title: "tic & travis - an overview"
author: "Patrick Schratz, Kirill Müller"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{tic and travis - an overview}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Most of the setup work that needs to be done for Travis CI is handled by the *travis* package. 
These are tasks like enabling the repo in [travis-ci.org](travis-ci.org), setting up SSH deployment keys for your repo on Travis and others.

After everything is set up the rest of the work goes to *tic*.
By this we mean the handling of the actual CI workflow: Which steps are going to be run, how the deployment is handled and so on.

In summary, the interaction is as follows:

- *travis*: Responsible for setting up all CI related tasks and taking care of permissions.

- *tic*: Responsible for the specification of the CI workflow (which stages are run, which commands are used).

To simplify setup, everything is handled by `tic::use_tic()`.
This function requires *travis* to be installed manually: otherwise, each CI run would have to install *travis* too which is not needed otherwise.
