---
title: "The advantages of tic"
author: "Patrick Schratz, Kirill Müller"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Kirill Müller}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

So, what's the advantage of using `tic` over the standard CI process?

- CI-agnostic workflow definitions (in R!)
- Simplified deployment (e.g. `pkgdown` site)
- Improved package checking via [rcmdcheck](https://github.com/r-lib/rcmdcheck)
- Robust caching approach

## CI-Agnostic workflows

What does "CI-Agnostic" mean and why do we need it?

You may have heard that multiple CI services exist in the wild.
Some only support specific operating systems or certain languages and for some you need to pay a monthly rate to use them.
What all have in common: They have their own way to specify their setup file, which is most often written in YAML and stored at the top-level directory of your repo.
This setup file controls what will be done in each run.

To give you an example how different these control files can be, take a look at these two examples from [Travis](https://github.com/tidyverse/dplyr/blob/master/.travis.yml) and [Appveyor](https://github.com/tidyverse/dplyr/blob/master/appveyor.yml).
While Travis is the only free CI service with an "official" support for R (maintained by the community, specifically by @jimhester), `Appveyor` currently requires quite some magic (e.g. `travis-tool.sh`) in the background to install a working R framework. 

We could list way more differences - but that's exactly the point when `tic` comes in!

- Rather than dealing with all the CI differences, `tic` enables the specification of the complete workflow in an external R script file `tic.R`.
- The commands specified in there will be understood on every CI service that is supported by `tic`.
- Furthermore, you can [emulate all the stages and steps locally](advantages.html#less-dependency-on-external-ci-control-commands) by calling `tic()`.
- You are independent from all the changes that are being made on the R setup for Travis or Appveyor ([more info]((advantages.html#less-dependency-on-external-ci-control-commands)).
- A `tic.R` workflow is usually shorter and easier to parse than a `.travis.yml` or `appveyor.yml` file.

So instead of learning how to specify specific tasks on different CI platforms, you only need to learn how to do with R commands.

## Easier deployment

You may know that CI services can be used to automatically deploy files. 
This means that these services can push certain files created during the build to repositories (Github, Gitlab, etc.).
A common use case is to build your `pkgdown` site and conditionally push changes to your repo.
This practice saves you from building the whole `pkgdown` site locally and then committing manually all the changed files - Travis will do it for you! 
`tic` takes care of all the setup work (setting up ssh keys, permission granting for the repo on Github and Travis).
In combination with `usethis::use_ci()` this whole preparation process is streamlined and needs only be called once for every repo by the user.

Today, it becomes more and more the standard to have a `pkgdown` site for a R package which presents all the well-written vignettes and function documentations in a nicely styled web version.
But this is only valuable if the information also reflects the most recent state of the repo.
Do not waste time on updating your site manually - automate such tasks!

`tic` initiates the deployment in the `.travis.yml` file with the following block:

```yml
before_deploy: R -q -e 'tic::before_deploy()'
deploy:
  provider: script
  script: R -q -e 'tic::deploy()'
  on:
    all_branches: true
```

Let's break down what happens here:

1. Travis executes `tic::before_deploy()` which will search for instructions regarding the `before_deploy()` stage in `tic.R`. By default this looks like

```r
if (Sys.getenv("BUILD_PKGDOWN") != "") {
  get_stage("before_deploy") %>%
    add_step(step_setup_ssh())
}
```

This block finally executes the function `step_setup_ ssh()` if the environment variable `"BUILD_PKGDOWN"` is set in the Travis build.
That is just one condition among many that you can set to run certain commands (or stages) conditionally (see [here](advanced.html#running-stages-conditionally) for more examples).
After the prerequisite of setting up an ssh key for the upcoming deployment has been finished, 

2. Travis is told to use a "script" (provider: script) for the deployment (which holds further instructions).
3. This "script" is then calling `tic::deploy()`.
4. All this is only happening on the `master` branch, meaning that other branches do not trigger a deploy with this condition set.

What happens now is that `tic::deploy()` again searches in `tic.R` for the "deploy" stage and then runs whatever you have specified there.

With the default template of `tic.R`, the following will be executed:

```r
get_stage("deploy") %>%
  add_step(step_build_pkgdown()) %>% 
  add_step(step_push_deploy())
```

First, `step_build_pkgdown()` will build your `pkgdown` site and afterwards (note the `pipe` operator), `step_push_deploy()` takes care to push the results to your repo.
By default this will be the `docs/` directory of the `master` branch.

## `rcmdcheck()` > R CMD check

Usually Travis will run `R CMD check` to check the R package.
`tic` instead uses  [`rcmdcheck`](https://github.com/r-lib/rcmdcheck), an optimized version of `R CMD check` developed by [Gabor Csardi](https://github.com/gaborcsardi).
It comes with several enhancements:

- Coloring of important steps on Travis, simplifying the readability of the log
- Enhanced and extended tracebacks of errors, especially errors in tests

Especially the extended log printing of errors is a huge advantage - often enough, the important information is not printed by Travis when using `R CMD check` making it hard for the user to debug the problem.

## Caching of packages

When using `tic` all dependencies (not only the ones of the package) are installed in the "before_install" stage. 
This has the advantage that all packages get added to the cache (even if they are just needed for deployment), speeding up subsequent builds substantially.

## Easier troubleshooting

`tic` comes with the ability to emulate the CI run locally and debug potential problems. 
This is possible because `tic.R` is a plain R file that will be sourced when calling `tic()`.
It will run all the stages and steps in the same order as it would happen on the CI service.

Sometimes CI builds error (even multiple times) and you don't know whether the error is caused by the CI service or by a wrong workflow specification on your side.

To make sure that you have no syntax errors in your `tic.R` file, all you need to do is to call `load_from_file()`.
In case you have errors, you will see them directly.
For example, removing a closing bracket on purpose in `tic.R` would return the following when calling `load_from_file()`:

```r
load_from_file()
Error in source(path, local = dsl) : tic.R:16:1: unexpected '}'
15:     add_step(step_push_deploy())
16: }
    ^
```

See [Troubleshooting: Running tic locally](advanced#troubleshooting-running-tic-locally) and [Troubleshooting: Entering the CI build](advanced#troubleshooting-entering-the-cI-build) for instructions on how to debug your CI build in more detail.

## Less dependency on external CI control commands

Most CI services come with no (native) support for the R programming language.
For Travis and Appveyor, the support is provided by the R community.
For example, [r.rb](https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb) controls what happens if you set `language: r` on Travis.
All of the commands and arguments specified there can also be set in `tic.R` using R syntax.
So you are no longer dependent on the syntax and restrictions coming from [r.rb](https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb) but able to control the whole CI workflow in a single R file.
