## tic GitHub Actions template: custom-deploy
## revision date: 2022-03-01
# [Custom header]
on:
  workflow_dispatch:
  push:
    branches:
    - main
    - master
  pull_request:
    branches:
    - main
    - master
  # for now, CRON jobs only run on the default branch of the repo (i.e. usually on master)
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 4 * * *"

name: tic

jobs:
  all:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          ### Custom configs (specify your own runners here)
          # [Custom matrix env var]
          # - { os: windows-latest, r: "release" }
          # [Custom matrix env var]
          # - { os: macOS-latest, r: "release", pkgdown: "true", latex: "true" }
          # [Custom matrix env var]
          # - { os: ubuntu-latest, r: "release" }
          # [Custom matrix env var]
          # - { os: ubuntu-latest, r: "devel" }

