#' @import backports
NULL

#' @importFrom utils packageName
load_from_file_ <- function(path = "tic.R", ..., mtime = file.mtime(path)) {
  env <- asNamespace(packageName())
  source_env <- new.env(parent = env)
  dsl <- create_dsl(envir = env)
  .dsl_storage$dsl <- dsl
  on.exit(.dsl_storage$dsl <- NULL, add = TRUE)
  source(path, local = source_env)
  dsl$get_stages()
}

#' Process a tic.R file
#'
#' Return a named list of stages generated by [source()]ing a file that uses the
#' tic [DSL].
#' The file is sourced only once per session, unless its modification timestamp
#' changes.
#'
#' @param path `[string]`\cr
#'   Path to the stage definition file, default: `"tic.R"`.
#' @param ... ignored
#' @param mtime `[POSIXt]`\cr
#'   For internal use, to detect changes to this file.
#'
#' @export
load_from_file <- memoise::memoise(load_from_file_)

#' tic's domain-specific language
#'
#' Functions to define stages and their constitutent
#' steps.
#'
#' @name DSL
NULL

#' @description
#' `get_stage()` returns a Stage object for a stage given by name.
#' This function only works when called by [load_from_file()].
#'
#' @param name `[string]`\cr
#'   The name for the stage.
#' @rdname DSL
#' @export
get_stage <- function(name) {
  get_current_dsl()$get_stage(name)
}

#' @description
#' `add_step()` adds a step to a stage, see [step_hello_world()]
#' and the links therein for available steps.
#'
#' @param stage `[Stage]`\cr
#'   A Stage object as returned by `get_stage()`.
#' @param step `[function]`\cr
#'   A function that constructs a Step object, such as [step_hello_world()].
#' @rdname DSL
#' @export
add_step <- function(stage, step) {
  stage$add_step(step, deparse(substitute(step), width.cutoff = 500, nlines = 1))
}

#' @description
#' `add_code_step()` is a shortcut for `add_step(step_run_code(...))`.
#'
#' @export
#' @inheritParams step_run_code
#' @rdname DSL
add_code_step <- function(stage, call = NULL, prepare_call = NULL) {
  call <- substitute(call)
  prepare_call <- substitute(prepare_call)
  step <- RunCode$new(.call = call, .prepare_call = prepare_call)
  stage$add_step(
    step,
    paste0(
      "step_run_code(",
      deparse(call, width.cutoff = 500, nlines = 1),
      if (!is.null(prepare_call)) {
        paste0(
          ", prepare_call = ",
          deparse(prepare_call, width.cutoff = 500, nlines = 1))
      },
      ")"
    )
  )
}

#' @description
#' `add_package_checks()` adds default steps related to package checks
#' to the `"before_install"`, `"install"`, `"script"` and `"after_success"`
#' stages:
#'
#' @inheritParams step_rcmdcheck
#' @rdname DSL
#' @export
#' @importFrom magrittr %>%
add_package_checks <- function(warnings_are_errors = TRUE,
                               notes_are_errors = FALSE,
                               args = c("--no-manual", "--as_cran")) {
  #' @description
  #' 1. A [step_rcmdcheck()] in the `"script"` stage, using the
  #'    `warnings_are_errors`, `notes_are_errors` and `args` arguments.
  get_stage("script") %>%
    add_step(
      step_rcmdcheck(
        warnings_are_errors = warnings_are_errors,
        notes_are_errors = notes_are_errors,
        args = args
      )
    )

  #' 1. A call to [covr::codecov()] in the `"after_success"` stage (only for non-interactive CIs)
  if (!ci()$is_interactive()) {
    get_stage("after_success") %>%
      add_code_step(covr::codecov(quiet = FALSE))
  }
}

#' @importFrom magrittr %>%
DSL <- R6Class(
  "DSL",

  public = list(
    initialize = function() {
      stage_names <- c(
        "before_install",
        "install",
        "after_install",
        "before_script",
        "script",
        "after_success",
        "after_failure",
        "before_deploy",
        "deploy",
        "after_deploy",
        "after_script"
      )

      private$stages <- lapply(stats::setNames(nm = stage_names), Stage$new)
    },

    get_stage = function(name) {
      stage <- self$get_stages()[[name]]
      if (is.null(stage)) {
        stop("Unknown stage ", name, ".", call. = FALSE)
      }
      stage
    },

    get_stages = function() {
      private$stages
    }
  ),

  private = list(
    stages = NULL
  )
)

create_dsl <- function(envir = parent.frame()) {
  dsl <- DSL$new()
  parent.env(dsl) <- envir
  dsl
}

.dsl_storage <- new.env(parent = emptyenv())

# Initialized in .onLoad()

get_current_dsl <- function() {
  .dsl_storage$dsl
}
