#' @importFrom utils packageName
load_from_file_ <- function(path = "tic.R", ..., mtime = file.mtime(path)) {
  dsl <- create_dsl(envir = asNamespace(packageName()))
  source(path, local = dsl)
  dsl$get_stages()
}

#' Process a tic.R file
#'
#' Return a named list of stages generated by evaluating a file that uses the
#' tic [DSL].
#' The file is read and evaluated only once, unless its modification timestamp
#' changes.
#'
#' @param path `[string]`\cr
#'   Path to the stage definition file, default: `"tic.R"`.
#' @param ... ignored
#' @param mtime `[POSIXt]`\cr
#'   For internal use, to detect changes to this file.
#'
#' @export
load_from_file <- memoise::memoise(load_from_file_)

#' tic's domain-specific language
#'
#' Functions to define stages and their constitutent
#' steps.
#'
#' @name DSL
NULL

#' @export
#' @param name `[string]`\cr
#'   The name for the stage.
#' @param private
#'   For internal use.
#' @rdname DSL
get_stage <- function(name, private = NULL) {
  if (!exists(name, private$stages)) {
    assign(name, Stage$new(name), private$stages)
  }
  get(name, private$stages)
}

#' @export
#' @param stage `[Stage]`\cr
#'   A Stage object as returned by `get_stage()`.
#' @param step `[function]`\cr
#'   A function that constructs a Step object, such as [step_hello_world()].
#' @rdname DSL
add_step <- function(stage, step) {
  stage$add_step(step, deparse(substitute(step), width.cutoff = 500, nlines = 1))
}

#' @importFrom magrittr %>%
DSL <- R6Class(
  "DSL",

  public = list(
    initialize = function() {
      private$stages <- new.env(parent = emptyenv())
    },

    get_stage = function(name) {
      get_stage(name, private)
    },

    get_stages = function() {
      as.list(private$stages)
    },

    add_step = function(stage, step) {
      add_step(stage, step)
    },

    add_task = function(stage, run, check = NULL, prepare = NULL) {
      stage$add_task(run, check, prepare)
    }
  ),

  private = list(
    stages = NULL
  )
)

create_dsl <- function(envir = parent.frame()) {
  dsl <- DSL$new()
  parent.env(dsl) <- envir
  dsl
}
